webhook-url: "http://example.com/api"
password: "your_password"

config-reloaded: "&l&6(C2H) §7Configuration successfully reloaded!"
no-permission-message: "&l&6(C2H) §cYou don't have permission to use this."
main-text: "&l&6(C2H) §7C2HTTP plugin. Author: @trassert"