name: ChatToHttp
version: 1.0
main: com.example.chattohttp.ChatToHttpPlugin
api-version: 1.21
author: trassert
description: Плагин, позволяющий отправлять чат по HTTP.
commands:
  c2h:
    description: Управление плагином
permissions:
  c2h.reload:
    description: "Разрешение на использование перезагрузки"
    default: op