name: ChatToHttp
version: ${project.version}
folia-supported: true
main: com.trassert.chattohttp.ChatToHttpPlugin
api-version: "1.20"
author: trassert
description: Плагин, позволяющий отправлять чат по HTTP.
commands:
  c2h:
    description: Plugin info
permissions:
  c2h.reload:
    description: Reload config
    default: op
